project:
  type: website

website:
  title: "Weiheng Wang - STA304 Quarto Website"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: flatly
    toc: true  
    css: styles.css 